###? Recuperar todas las peliculas
GET http://localhost:3000/movies

###? Recuperar una pelicula por id
GET http://localhost:3000/movies/f462239c-6242-11ef-bebb-d85ed35a1edc

###? Recuperar todas las peliculas por un genero
GET http://localhost:3000/movies?genre=ACTION

###? Crear una pelicula con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
    "sql": "SELECT * FROM movies",
    "title": "El Padrino",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime", 
        "Drama",
        "Action"
    ]
}

###? Borrar una pelicula
DELETE http://localhost:3000/movies/cd3f5b76-6243-11ef-bebb-d85ed35a1edc

###? Actualizar una pelicula
PATCH http://localhost:3000/movies/45722f03-6244-11ef-bebb-d85ed35a1edc
Content-Type: application/json

{
    "year": 2000
}